export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const SORT_BY = 'SORT_BY';
export const SET_USER = 'SET_USER';
export const TOGGLE_VIEW = 'TOGGLE_VIEW';
